language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install numpy matplotlib"
# command to run tests
script: doctests

before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update

install:
  - sudo apt-get install libcv-dev libcvaux-dev libhighgui-dev libopencv-dev

script:
  - make CONFIG=debug
  - make nomulti CONFIG=debug
  - make -C opencv2fx CONFIG=debug